### ISSUE TITLE
请教一下数据准备的问题

### ISSUE THREAD

**Issue by Alicebupt** [qiny1012/kaldi_x-vector_aishell#6]
楼主你好，我在new_04的时候出现了以下问题：
steps/make_mfcc.sh --mfcc-config conf/mfcc.conf --nj 20 --cmd utils/parallel/run.pl --mem 10G data/train_aug exp/make_mfcc feature/mfcc
utils/validate_data_dir.sh: Successfully validated data-directory data/train_aug
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: It seems not all of the feature files were successfully procesed (360294 != 480392); consider using utils/fix_data_dir.sh data/train_aug
steps/make_mfcc.sh: Less than 95% the features were successfully generated. Probably a serious error.

是因为前面数据增强准备的数据有问题么？用的是和您一样的数据集。

**Comment by Alicebupt** [comment]
您也可以加我的vx：A18810559266，备注git
初学kaldi，希望能和您多探讨一下。感谢！

**Comment by qiny1012** [comment]
**您好，您的问题的原因是加混响的部分语音，找不到混响内容。**

**请参考这个解决方案：**

![image](https://user-images.githubusercontent.com/32615944/129851177-26fe07bb-487e-477e-8f52-832691057910.png)

**Comment by Alicebupt** [comment]
非常感谢楼主及时的回复，我刚刚改了一下，但是还是同样的错误，不知道是哪还不对

**Comment by Alicebupt** [comment]
另外，还有一个问题想问您，我从哪可以看生成的文件是否有数据库的前缀呢？我现在是跑new_04进行验证，每次跑都要两个多小时，我怎么能更快的定位问题是否解决呢？感谢！！

**Comment by qiny1012** [comment]
new_04是提取mfcc特征，需要很长的时间。可以看显示的log，如果出现“It seems not all of the feature files were successfully procesed (360294 != 480392);” 类似的log，就是缺少加混响内容。另外，可以查看exp/make_mfcc下的log，里面应该具体的文件缺失报错。

**Comment by Alicebupt** [comment]
已经成功定位问题了，写路径的时候多写了一层，感谢楼主的及时回复！！
